# routing.yaml
# repos     - 所有要下载的仓库
# routing   - 每个 suite 的包匹配规则
#             pattern:  包名 glob，版本号位用 * 占位
#             version:  auto = 拉最新版本, 指定数字 = 锁定版本
#             不写 version 默认就是 auto

repos:
  - Roboparty/roboparty_base
  - Roboparty/roboparty_description
  - Roboparty/roboparty_go
  - Roboparty/roboparty_motors
  - Roboparty/roboparty_all
  - Roboparty/roboparty_example
  - Roboparty/roboparty_imu
  - Roboparty/roboparty_bms
  - Roboparty/roboparty_inference
  - Roboparty/roboparty_rp_server
  - Roboparty/roboparty_ecatfd_master
  - Roboparty/roboparty_image
  - Roboparty/robopi_firmware
  - Roboparty/soem-deb
  - Roboparty/igh-deb
  - wentywenty/zlg-deb
  - wentywenty/f81601a-deb
  - wentywenty/hpm-dfu-deb

routing:
  common:
    - pattern: "roboparty-base_*_all.deb"
    - pattern: "roboparty-description_*_all.deb"
    - pattern: "roboparty-go_*_all.deb"
    - pattern: "roboparty-example_*_all.deb"
    - pattern: "roboparty-all_*_all.deb"

    - pattern: "roboparty-motors_*_amd64.deb"
    - pattern: "roboparty-motors_*_arm64.deb"
    - pattern: "roboparty-imu_*_amd64.deb"
    - pattern: "roboparty-imu_*_arm64.deb"
    - pattern: "roboparty-bms_*_amd64.deb"
    - pattern: "roboparty-bms_*_arm64.deb"
    - pattern: "roboparty-inference_*_amd64.deb"
    - pattern: "roboparty-inference_*_arm64.deb"
    - pattern: "roboparty-rp-server_*_all.deb"
    - pattern: "roboparty-ecatfd-master_*_amd64.deb"
    - pattern: "roboparty-ecatfd-master_*_arm64.deb"

    - pattern: "libsoem-dev_*_amd64.deb"
    - pattern: "libsoem-dev_*_arm64.deb"
    - pattern: "orangepi-firmware_*_arm64.deb"
    - pattern: "ethercat-igh_*_amd64.deb"
    - pattern: "ethercat-igh_*_arm64.deb"

    - pattern: "f81601a-dkms_*_all.deb"
    - pattern: "usbcanfd-dkms_*_all.deb"
    - pattern: "hpm-manufacturing-tool_*_amd64.deb"

  robopi1:
    - pattern: "linux-u-boot-current-robopi1_*_arm64.deb"
      version: 1.2.8
    - pattern: "linux-image-current-rockchip-rk3588_*_arm64.deb"
      version: 1.2.8
    - pattern: "linux-dtb-current-rockchip-rk3588_*_arm64.deb"
      version: 1.2.8
    - pattern: "linux-headers-current-rockchip-rk3588_*_arm64.deb"
      version: 1.2.8
    - pattern: "linux-image-current-rockchip-rk3588-dbg_*_arm64.deb"
      version: 1.2.8

  robopi2:
    - pattern: "linux-u-boot-current-robopi2_*_arm64.deb"
      version: 1.0.9
    - pattern: "linux-image-current-rockchip-rk3588_*_arm64.deb"
      version: 1.0.9
    - pattern: "linux-dtb-current-rockchip-rk3588_*_arm64.deb"
      version: 1.0.9
    - pattern: "linux-headers-current-rockchip-rk3588_*_arm64.deb"
      version: 1.0.9
    - pattern: "linux-image-current-rockchip-rk3588-dbg_*_arm64.deb"
      version: 1.0.9
      